version: '3.8'

services:
  # 1. PostgreSQL DB
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. MQTT 브로커 (Mosquitto)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  # 3. Spring Boot 백엔드 서버
  backend:
    build: .
    container_name: spring_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iot_db
      - MQTT_BROKER_URL=tcp://mosquitto:1883
    depends_on:
      - postgres
      - mosquitto

volumes:
  postgres_data: